name: Go
on: [push]
jobs:
  linux:
      name: Go ${{ matrix.go }} on Ubuntu
      runs-on: ubuntu-latest
      strategy:
        matrix:
          go: ['1.16']
      env:
        name: ubuntu
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go }}

        - name: Build
          run: |
            cd src
            source ./make.bash

        #- name: Test
        #  run: |
        #    cd src
        #    source ./run.bash --no-rebuild

        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: ${{ env.name }}
            path: |
              bin/
            if-no-files-found: error
